using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace MeetingNotes.Data.Migrations
{
    /// <inheritdoc />
    public partial class not_autogenerated_keys : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "22e40406-8a9d-2d82-912c-5d6a640ee696",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "150e3d91-b30c-4080-8f22-d87f47e58363", "AQAAAAIAAYagAAAAEC4/ulszc8XTqk/ilIjNMFXC5riARxZ+7v90V9y5L0PVK3j6RPCw1NgAGnIsWlE+vg==", "1cddc618-dceb-47ac-99ae-f15ad3d9585f" });
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.UpdateData(
                table: "AspNetUsers",
                keyColumn: "Id",
                keyValue: "22e40406-8a9d-2d82-912c-5d6a640ee696",
                columns: new[] { "ConcurrencyStamp", "PasswordHash", "SecurityStamp" },
                values: new object[] { "83031192-968a-4184-83b0-e6143ec1c737", "AQAAAAIAAYagAAAAEHkWyTt2YUsF/gkgaOdN2r74sGrqI4v60qSZ7HkIZEAv2nmx9C4vTHSIQY5c5x+K1w==", "bfbd3beb-3337-4c26-8440-4242cca49cb7" });
        }
    }
}
